### ISSUE TITLE
invalidProtocolVersion(255) when trying to connect to MySQL on Ubuntu

### ISSUE THREAD

**Issue by bporter95** [vapor/fluent-mysql-driver#215]
### Describe the bug

When trying to connect to MySQL from Vapor running on Ubuntu, I am receiving the following error:
`invalidProtocolVersion(255)`

Meanwhile, I have no issues with connecting when running Vapor on my Mac locally

### Environment
I am running Vapor in a Docker Container on an Ubuntu 22 server. I have also tried running vapor outside of docker using the cli.
I am running MySQL 8.0.32-0ubuntu0.22.04.2

* Vapor Framework version:
  * Vapor: 4.69.1
  * Fluent 4.6.0
  * Fluent MySQL Driver 4.2.0
* OS version: Ubuntu 22.04.2

**Comment by T2Je** [comment]
Did you find any solution?

**Comment by bporter95** [comment]
In my case, it ended up being a MySQL credentials error (nothing related to a bug in Fluent)

**Comment by gwynne** [comment]
Hey, I wanted to follow up on this quickly - while it's true that the immediate cause of the problem was on the server end, Fluent should not have been reporting that particular, very unhelpful error. This particular symptom occurs when the server sends an `ERR_Packet`, which starts with an `0xff (255)` marker byte, immediately upon connection, instead of the expected `HandshakeV10` greeting, whose first byte is expected to be the advertised protocol version. It's is an entirely valid thing for the server to do, but the wire protocol implementation in MySQLNIO currently mishandles it by immediately rejecting the 255 value where it expected to find a protocol version number (specifically, 10), rather than checking to see if the packet represents an error. As a result, the error message the server sent is lost.

A large-scale rewrite of MySQLNIO to address this and dozens of other issues is currently in progress, hopefully I'll have it ready for at least a preview soon.
